# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tdprint}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:appuser}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JACKSON
# ===============================
spring.jackson.serialization.indent_output=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO

# ===============================
# CORS (custom property)
# ===============================
cors.allowed-origins=http://localhost:5173


## JWT

jwt.secret=${JWT_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
jwt.expiration=${JWT_EXPIRATION:800000000}

## File Uploads
file.upload-dir=./uploads